description: "Act as an agent with access to helpful tools like memory and internet search"
version: "1.0"
arguments:
  - name: "task"
    description: "The specific task"
    required: true
metadata:
  tags:
    - memory
    - google
  suggested_use: "Use for geneal purpose tasks that need access to a memory and internet"
  output_format: "markdown"