description: "Instruct to generate an SVG visual"
version: "1.0"
arguments:
  - name: "design"
    description: "outline briefly the design, including the aspect ratio, colors, and any specific elements you want included"
    required: true
  - name: "content"
    description: "describe what the SVG should semantically contain"
    required: true
metadata:
  tags:
    - svg
  suggested_use: "Use to generate an SVG visual" 
  output_format: "markdown"